import Layout from "@/components/Layout";

const Privacy = () => {
  return (
    <Layout>
      <section className="container pt-32 pb-16">
        <p className="text-sm text-primary font-medium uppercase tracking-widest mb-3">Legal</p>
        <h1 className="font-display font-bold text-5xl sm:text-6xl tracking-tight">
          Privacy <span className="text-gradient">policy</span>
        </h1>
      </section>

      <section className="container pb-24 space-y-6">
        <article className="rounded-2xl border border-border bg-gradient-card p-6">
          <h2 className="font-semibold text-lg">Information we collect</h2>
          <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
            We collect details you provide during account creation, checkout, and support communication. We also collect
            basic device and usage data to improve site performance and reliability.
          </p>
        </article>

        <article className="rounded-2xl border border-border bg-gradient-card p-6">
          <h2 className="font-semibold text-lg">Cookies and Analytics</h2>
          <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
            We use cookies and similar technologies to enhance your browsing experience. This website uses Google Analytics, 
            a web analytics service provided by Google LLC ("Google"). Google Analytics uses cookies to help us analyze how 
            users interact with our site.
          </p>
          <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
            The information generated by the cookie about your use of the website (including your IP address) will be 
            transmitted to and stored by Google on servers in the United States. Google will use this information for the 
            purpose of evaluating your use of the website, compiling reports on website activity, and providing other 
            services relating to website activity and internet usage.
          </p>
          <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
            You can learn more about how Google uses data when you use our site by visiting{" "}
            <a 
              href="https://www.google.com/policies/privacy/partners/" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              How Google uses information from sites or apps that use our services
            </a>.
          </p>
          <p className="mt-3 text-sm text-muted-foreground leading-relaxed">
            You may refuse the use of cookies by selecting the appropriate settings on your browser. However, please note 
            that if you do this, you may not be able to use the full functionality of this website. You can also opt-out 
            from being tracked by Google Analytics by installing the{" "}
            <a 
              href="https://tools.google.com/dlpage/gaoptout" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              Google Analytics Opt-out Browser Add-on
            </a>.
          </p>
        </article>

        <article className="rounded-2xl border border-border bg-gradient-card p-6">
          <h2 className="font-semibold text-lg">How we use your information</h2>
          <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
            Data is used to process orders, provide support, communicate updates, and prevent fraud. We do not sell
            personal data to third parties.
          </p>
        </article>

        <article className="rounded-2xl border border-border bg-gradient-card p-6">
          <h2 className="font-semibold text-lg">Your rights</h2>
          <p className="mt-2 text-sm text-muted-foreground leading-relaxed">
            You may request access, correction, or deletion of your personal data by contacting support. You also have 
            the right to opt-out of analytics tracking using the methods described above.
          </p>
        </article>
      </section>
    </Layout>
  );
};

export default Privacy;
